### ISSUE TITLE
boot-kali does nothing... edit now bootkali works from # on the s9 but not on the s8... hmm weird cause ive had your script working on the s9 before and the s8... atleast I can boot chroot from termux now im unsure why your script isnt working Im guessing this has to do with some directories and permissions?

### ISSUE THREAD

**Issue by GMANNMODS** [name-is-cipher/boot-nethunter#10]
I've reinstalled it numerous times and still it won't boot the chroot in termux after I type "boot-kali" anywhere not even in a root termux terminal #. I can't figure out why maybe cause I'm on Android 10 maybe scoped storage?? Snapdragon Galaxy s9 plus android 10. It works great on my s8 plus on Android 7 so I'm confused and thanks for making this man. If you tell me how to get logs I can for you... I remember bootkali used to work in termux su # termux a long time ago without your script so I'm glad you made this cause the newest nethunter terminal is crap. Please let me know if you can help me get in running on my s9 plus as we are working on a custom Nethunter kernel right now so I need termux stability.

**Comment by cipherswami** [comment]
Hi, sorry for late reply.

Can you just give me the output of boot-kali

**Comment by cipherswami** [comment]
NO response closing the issue
