### ISSUE TITLE
Errors same as Kali terminal 

### ISSUE THREAD

**Issue by bobbypfreely** [name-is-cipher/boot-nethunter#3]
Once I hit boot-kali it throws a bunch of errors. Mainly can't find this or that, I'll upload a shot. I followed directions copy a paste. New install of termux.... After manually adding the folders it couldn't find only error is can't find /bin/bash. Which is there and set to 0777 so idk what I can do, maybe adding bash to the home directory it created?

**Comment by cipherswami** [comment]
Hi @bobbypfreely ,

From what you have described above, all I can conclude is, your kali chroot (Nethunter) is broken. 
Boot Nethunter, only boots kali chroot in Termux. 

As you are getting the same error in nethunter terminal, it is a an issue of nethunter apk. Checkout the source code for  [Nethunter apk](https://gitlab.com/kalilinux/nethunter/apps/kali-nethunter-app), and try to find solution for your issue there.

If you want my suggestion, I would recommend you to completely uninstall and then install nethunter.
Do Reply weather I understood your problem or is there something else.

**Comment by bobbypfreely** [comment]
I'll give it a shot, I figured it was Android 10 and the crazy file organization and not letting anything access anything. I'll close it out after I try and update you as well

**Comment by cipherswami** [comment]
I don't think so it is a problem with Andriod 10 as I'm an android 10 user myself. 
And yes do try.

**Comment by bobbypfreely** [comment]
Ok so not just Android 10 but a Motorola, they are awesome for customizing
lacking in sensibility

**Comment by bobbypfreely** [comment]
Holy crud I'm sorry dude, you're awesome that worked actually. Now just to
fine tune it, metasploit needs built on the PC and idk if the USB or hid
works but thanks to you I got the external wifi adapter to work like a charm

**Comment by cipherswami** [comment]
Good to know.
