### ISSUE TITLE
貌似并不起到作用？

### ISSUE THREAD

**Issue by Jpkie** [name-is-cipher/boot-nethunter#6]
He doesn't seem to be working? My nmap still prompts for insufficient permissions🤔🤔🤔
![Screenshot_2023-06-18-01-04-36-062_com termux](https://github.com/name-is-cipher/boot-nethunter/assets/104114507/8cd6e3d1-846f-437f-b7f2-8f6e11de9587)
. Of course, it's also possible that it's not😭😭😭
![Screenshot_2023-06-18-01-05-15-223_com termux](https://github.com/name-is-cipher/boot-nethunter/assets/104114507/f1f2a6dd-7f98-498b-8f76-1447d55cff75)

**Comment by cipherswami** [comment]
It seems like you don't have chroot. And you are running it inside a proot environment.

chroot and proot are two different things, boot-nethunter is to start nethunter's chroot inside termux.
